List<String> cityNames = [
  'Bath',
  'Birmingham*',
  'Bradford*',
  'Brighton & Hove',
  'Bristol*',
  'Cambridge',
  'Canterbury*',
  'Carlisle',
  'Chelmsford',
  'Chester*',
  'Chichester',
  'Colchester',
  'Coventry*',
  'Derby',
  'Doncaster',
  'Durham',
  'Ely',
  'Exeter*',
  'Gloucester',
  'Hereford',
  'Kingston-upon-Hull*',
  'Lancaster',
  'Leeds*',
  'Leicester*',
  'Lichfield',
  'Lincoln',
  'Liverpool*',
  'London*',
  'Manchester*',
  'Milton Keynes',
  'Newcastle-upon-Tyne*',
  'Norwich*',
  'Nottingham*',
  'Oxford*',
  'Peterborough',
  'Plymouth*',
  'Portsmouth*',
  'Preston',
  'Ripon',
  'Salford',
  'Salisbury',
  'Sheffield*',
  'Southampton*',
  'Southend-on-Sea',
  'St Albans',
  'Stoke on Trent*',
  'Sunderland',
  'Truro',
  'Wakefield',
  'Wells',
  'Westminster*',
  'Winchester',
  'Wolverhampton',
  'Worcester',
  'York*',
];

List<String> countyNames = [
  'Avon',
  'Bedfordshire',
  'Berkshire',
  'Buckinghamshire',
  'Cambridgeshire',
  'Cheshire',
  'Cornwall',
  'Cumbria',
  'Derbyshire',
  'Devon',
  'Dorset',
  'Durham',
  'Essex',
  'Gloucestershire',
  'Greater London',
  'Hampshire',
  'Herefordshire',
  'Hertfordshire',
  'Isle of Wight',
  'Kent',
  'Lancashire',
  'Leicestershire',
  'Lincolnshire',
  'Merseyside',
  'Norfolk',
  'Northamptonshire',
  'Northumberland',
  'Nottinghamshire',
  'Oxfordshire',
  'Rutland',
  'Schools',
  'Shropshire',
  'Somerset',
  'Staffordshire',
  'Suffolk',
  'Surrey',
  'Sussex',
  'Tyne and Wear',
  'Warwickshire',
  'West Midlands',
  'Wiltshire',
  'Worcestershire',
  'Yorkshire',
];
