List<String> subCategoryItems = [
  'Traps & Wastes',
  'Cable Management',
  'Cables & Flexes',
  'Power Distribution',
  'Extention Leads & Cable Reels',
  'Alarms & Detectors',
  'EV Charging',
  'TV, Aerials, Data & Telecoms',
  'Timers',
  'Electrical Test Equipment',
  'Batteries & Powerbanks',
  'Smart Electrical',
  'Timers',
  'Electrical Test Equipment',
  'Batteries & Powerbanks',
  'Smart Electrical',
];
